modLoader="javafml"
loaderVersion="[35,)"
license="All rights reserved"

[[mods]]
    modId="icsaba_mounted_perspective"
    version="${file.jarVersion}"
    displayName="Mounted Perpective"
    authors="https://github.com/csaba-ilonka"
    description='''This mod automatically changes the perspective to 3rd person when the player mounts an entity, and changes it back to 1st person when unmounting the same entity.'''
    # A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
    #updateJSONURL="https://change.me.example.invalid/updates.json" #optional

[[dependencies.icsaba_mounted_perspective]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.icsaba_mounted_perspective]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
